### ISSUE TITLE
#2. Find the name and height of the shortest player in the database. How many games did he play in? What is the name of the team for which he played?

### ISSUE THREAD

**Issue by MrBardot** [NSS-Full-Time-Data-Analytics-2/lahman-baseball-data-snickers#2]
people table 
Join teams table on player id. 
Join appearances table on player id 
WHERE height condition
*what unit of measurement. 

maybe 2 queries?

**Comment by hrubel** [comment]
SELECT people.namegiven, people.height, teams.name AS team, teams.g AS games_played
FROM people
JOIN appearances
ON people.playerid = appearances.playerid
JOIN teams
ON teams.teamid = appearances.teamid
ORDER BY height
LIMIT 1;

**Comment by hrubel** [comment]
SELECT people.namegiven, people.height, teams.name AS team, appearances.g_all AS games_played
FROM people
JOIN appearances
ON people.playerid = appearances.playerid
JOIN teams
ON teams.teamid = appearances.teamid
ORDER BY height
LIMIT 1;
