### ISSUE TITLE
#3. Find all players in the database who played at Vanderbilt University. Create a list showing each player’s first and last names as well as the total salary they earned in the major leagues. Sort this list in descending order by the total salary earned. Which Vanderbilt player earned the most money in the majors?

### ISSUE THREAD

**Issue by MrBardot** [NSS-Full-Time-Data-Analytics-2/lahman-baseball-data-snickers#3]
salaries table JOIN people table 
JOIN schools table ON college playing USING school id

SELECT namefirst, namelast, salary, schoolname
FROM salaries as s
INNER JOIN people AS p 
on s.playerid=p.playerid 
INNER JOIN collegeplaying as c
on c.playerid=s.playerid
INNER JOIN schools as sc
ON sc.schoolid=c.schoolid
WHERE schoolname = 'Vanderbilt University'
ORDER BY salary DESC;

**Comment by leli-1** [comment]
can you assign this to me
