### ISSUE TITLE
8. Using the attendance figures from the homegames table, find the teams and parks which had the top 5 average attendance per game in 2016 (where average attendance is defined as total attendance divided by number of games). Only consider parks where there were at least 10 games played. Report the park name, team name, and average attendance. Repeat for the lowest 5 average attendance.

### ISSUE THREAD

**Issue by tthoang** [NSS-Full-Time-Data-Analytics-2/lahman-baseball-data-snickers#6]
FIND top 5 for avg attend in 2016
FIND bottom 5 for avg attend in 2016 
homegames table JOIN parks table 
join teams table 
avg attendance = total attendance

**Comment by MrBardot** [comment]
TOP 5
SELECT parks.park_name,homegames.park, team, attendance,games, (attendance/games) AS average_attendance
FROM homegames 
INNER JOIN parks
ON homegames.park = parks.park
WHERE games > 10
	AND year = '2016'
ORDER BY average_attendance DESC
LIMIT 5;

BOTTOM 5
SELECT parks.park_name,homegames.park, team, attendance,games, (attendance/games) AS average_attendance
FROM homegames 
INNER JOIN parks
ON homegames.park = parks.park
WHERE games > 10
	AND year = '2016'
ORDER BY average_attendance 
LIMIT 5;
