### ISSUE TITLE
#5. Find the average number of strikeouts per game by decade since 1920. Round the numbers you report to 2 decimal places. Do the same for home runs per game. Do you see any trends?

### ISSUE THREAD

**Issue by MrBardot** [NSS-Full-Time-Data-Analytics-2/lahman-baseball-data-snickers#8]
FROM teams? 
windows function for avg # 
generate series (MIN year, MAX  end date, 10)  

*ask mahesh about strikeout (per team # so per game, how many games per decade/)

FOR THE AVERAGE NUMBER OF STRIKEOUTS: 

(Number of strikeouts per decade/
HOW many games by the decades)

YALL. I'M SO CLOSE. 

WITH ten_years AS (SELECT generate_series(1920, MAX(yearid), 10) AS decade,	
				   generate_series(1, 10, 1) as num
				  FROM teams)
SELECT generate_series(1, 10, 1) as num,
	(SUM(so) OVER (PARTITION BY ten_years.decade))/(SUM(g) OVER (PARTITION BY ten_years.decade)) AS avg_so_per_decade
FROM teams INNER JOIN ten_years ON teams.num = ten_years.num;

**Comment by tthoang** [comment]
`SELECT yearid/10 * 10 AS decade, 
	ROUND(((SUM(so)::float/SUM(g))::numeric), 2) AS avg_so_per_game,
	ROUND(((SUM(so)::float/SUM(ghome))::numeric), 2) AS avg_so_per_ghome
FROM teams
WHERE yearid >= 1920 
GROUP BY decade
ORDER BY decade;`
